(in-package #:cl-exec-sandbox/tests)

(defun windows-test-write (path text)
  (ensure-directories-exist path)
  (with-open-file (stream path :direction :output :if-exists :supersede)
    (write-string text stream)))

(defun run-windows-tests ()
  "Exercise native AppContainer enforcement, rather than merely checking launch flags."
  #-win32 (error "The Windows enforcement tests require Windows.")
  #+win32
  (let* ((root (merge-pathnames
                (format nil "sandbox-Lukáš-žluťoučký-~36R/" (get-universal-time))
                (uiop:temporary-directory)))
         (workspace (merge-pathnames "workspace/" root))
         (programs (merge-pathnames "programs/" root))
         (read-root (merge-pathnames "read only/" root))
         (outside (merge-pathnames "outside/private.txt" root))
         (read-file (merge-pathnames "data.txt" read-root))
         (denied (merge-pathnames "secret/" workspace))
         (secret (merge-pathnames "data.txt" denied))
         (output (merge-pathnames "result.txt" workspace))
         (metadata (merge-pathnames ".git/config" workspace))
         (payload (merge-pathnames "windows-child.exe" programs))
         (policy (appcontainer-sandbox-policy :workspace-roots (list workspace)
                                              :read-roots (list programs read-root)))
         (checks 0))
    (labels ((check (truth description)
               (unless truth (error "Windows sandbox test failed: ~A" description))
               (incf checks))
             (run (arguments &optional (selected-policy policy) timeout)
               (run-sandboxed (uiop:native-namestring payload) arguments
                              :policy selected-policy :working-directory workspace
                              :timeout (or timeout 20) :output-limit 8192 :error-output-limit 8192))
             (status (arguments expected &optional (selected-policy policy))
               (let ((result (run arguments selected-policy)))
                 (unless (= expected (sandbox-result-exit-code result))
                   (format t "~&Resolved policy: ~S~%"
                           (mapcar (lambda (rule)
                                     (list (cl-exec-sandbox::resolved-filesystem-rule-access rule)
                                           (cl-exec-sandbox::resolved-filesystem-rule-path rule)))
                                   (cl-exec-sandbox::rules--resolve-rules selected-policy workspace)))
                   (when (second arguments)
                     (format t "~&Active ACL: ~A~%"
                             (sandbox-result-output (run (list "acl" (second arguments)) selected-policy)))))
                 (check (= expected (sandbox-result-exit-code result))
                        (format nil "~S: expected ~D, got ~D; ~A"
                                arguments expected (sandbox-result-exit-code result)
                                (sandbox-result-error-output result)))))
             (native (path) (uiop:native-namestring path)))
      (unwind-protect
           (progn
             (dolist (file (list outside read-file secret metadata))
               (windows-test-write file "private data"))
             (ensure-directories-exist payload)
             (uiop:copy-file
              (merge-pathnames "build/windows-child.exe"
                               (asdf:system-source-directory :cl-exec-sandbox)) payload)
             (check (eq (getf (sandbox-capabilities) :backend) :appcontainer) "native backend discovered")
             (status (list "identity") 0)
             (status (list "write" (native output)) 0)
             (check (probe-file output) "workspace write actually created a file")
             (status (list "rename" (native output) (native (merge-pathnames "renamed.txt" workspace))) 0)
             (status (list "delete" (native (merge-pathnames "renamed.txt" workspace))) 0)
             (status (list "write-delete" (native output)) 0)
             (status (list "read" (native read-file)) 0)
             (status (list "write" (native read-file)) 5)
             (status (list "read" (native outside)) 0 (unrestricted-sandbox-policy))
             (status (list "read" (native outside)) 5)
             (status (list "write" (native outside)) 5)
             (status (list "write" (native metadata)) 5)
             (status (list "delete" (native metadata)) 5)
             (status (list "change-acl" (native metadata)) 5)
             (let ((result (run (list "rename" (native (merge-pathnames ".git/" workspace))
                                             (native (merge-pathnames "moved/" workspace))))))
               (check (member (sandbox-result-exit-code result) '(5 32)) "metadata root cannot be renamed"))
             (let ((denied-policy
                     (make-sandbox-policy
                      :workspace-roots (list workspace)
                       :mount-proc-p nil :isolate-processes-p nil
                      :filesystem-rules
                      (append (sandbox-policy-filesystem-rules policy)
                              (list (make-filesystem-rule :kind :path :path denied :access :deny))))))
               (status (list "read" (native secret)) 5 denied-policy))
             (check (string= (uiop:read-file-string outside) "private data") "outside file unchanged")
             (check (string= (uiop:read-file-string metadata) "private data") "metadata unchanged")
             (let ((result (run (list "echo" "" "two words" "a\"b" "C:\\path\\"))))
               (check (zerop (sandbox-result-exit-code result)) "argument probe ran")
               (check (search "[]" (sandbox-result-output result)) "empty argument preserved")
               (check (search "[a\"b]" (sandbox-result-output result)) "embedded quote preserved")
               (check (search "[C:\\path\\]" (sandbox-result-output result)) "trailing backslash preserved"))
             (let ((server (make-instance 'sb-bsd-sockets:inet-socket :type :stream :protocol :tcp)))
               (unwind-protect
                    (progn
                      (sb-bsd-sockets:socket-bind server #(127 0 0 1) 0)
                      (sb-bsd-sockets:socket-listen server 8)
                      (let ((port (nth-value 1 (sb-bsd-sockets:socket-name server))))
                        (status (list "connect" (write-to-string port)) 0 (unrestricted-sandbox-policy))
                        (status (list "connect" (write-to-string port)) 10013)))
                 (sb-bsd-sockets:socket-close server)))
             (dolist (mode '("spawn-exit" "spawn"))
               (let* ((late (merge-pathnames (format nil "~A.txt" mode) workspace))
                      (result (run (list mode (native late)) policy (if (string= mode "spawn") 0.75 20))))
                 (if (string= mode "spawn")
                     (check (sandbox-result-timed-out-p result) "timeout reported")
                     (check (zerop (sandbox-result-exit-code result)) "descendant created before parent exit"))
                 (sleep 2)
                 (check (not (probe-file late)) "process-tree termination prevented late write")))
             (dolist (unsupported
                       (list (read-only-sandbox-policy)
                             (workspace-write-sandbox-policy :workspace-roots (list workspace))
                             (unrestricted-sandbox-policy :network :isolated)))
               (check (handler-case (progn (run '("identity") unsupported) nil)
                        (sandbox-unavailable () t))
                      "unsupported whole-host policies fail before execution"))
             (format t "~D Windows sandbox enforcement checks passed.~%" checks))
        (uiop:delete-directory-tree root :validate t :if-does-not-exist :ignore)))))
